//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group3_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Answer
    {
        public int answerId { get; set; }
        public string answerName { get; set; }
        public Nullable<bool> isAswer { get; set; }
        public Nullable<int> quesid { get; set; }
    }
}
