//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Group3_Project.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Content
    {
        public int ContentID { get; set; }
        public string Title { get; set; }
        public string Contents { get; set; }
        public string Example { get; set; }
        public Nullable<int> lessonId { get; set; }
    }
}
